---
- name: Restart crowdsec
  ansible.builtin.systemd:
    name: crowdsec
    state: restarted

- name: Restart crowdsec firewall bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
