---
node_exporter_version: "1.8.2"
# По умолчанию слушаем localhost only. Для prod проброс через wireguard / ssh-tunnel
# или whitelist через firewall (allow from prometheus-server-ip).
node_exporter_listen_address: "127.0.0.1:9100"
# Collectors. Default набор минус потенциально-тяжёлые. Полный list:
# https://github.com/prometheus/node_exporter#collectors
node_exporter_enabled_collectors:
  - cpu
  - diskstats
  - filesystem
  - loadavg
  - meminfo
  - netdev
  - netstat
  - sockstat
  - stat
  - systemd
  - time
  - vmstat
